<!DOCTYPE html>
  <html>
  <head>
    <link href="css/forum/style.css" rel="stylesheet">
    <link href="css/forum/style-1.1.css" rel="stylesheet">
    <link href="css/forum/style-1.2.css" rel="stylesheet">
    <link href="css/forum/font-awesome/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
        <link href="<?php echo $sk['config']['theme_url']; ?>/css/font-awesome/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->
      
    <script src="js/forum/jquery-ui-1.10.4.custom.min.js"></script>
    <script src="js/forum/jquery.ui.touch-punch.min.js"></script>
    <script src="js/forum/jquery-timeago.js"></script>
    <script src="js/forum/jquery.form.min.js"></script>
    <script>
    function SK_source(){
        return 'http://forum-hatunot.com/forum-custom/script/request.php';
    }
    function SK_pageSource() {
        return 'http://forum-hatunot.com/forum-custom/script/page.php';
    }
    </script>
    <script src="js/forum/script.js"></script>
</head>
<body>
    <style type="text/css">
        .ui-overlay-b, .ui-page-theme-b, .ui-page-theme-b .ui-panel-wrapper{
            text-shadow: none !important;
        }
        .header-wrapper {
            background:linear-gradient(#4C4C4C, #151515) !important;
            border-bottom: none !important;
            
        }
        .header-join-wrapper{
            color: white !important;
        }
		.header-user-info{
        	display: none !important;
        }
    </style>

    <?php echo SK_getPage('header/content'); ?>
    <div class="page-wrapper">
        <?php echo $sk['content']; ?>
    </div>    
</body>


</html>