<!DOCTYPE html>
<!--
    Licensed to the Apache Software Foundation (ASF) under one
    or more contributor license agreements.  See the NOTICE file
    distributed with this work for additional information
    regarding copyright ownership.  The ASF licenses this file
    to you under the Apache License, Version 2.0 (the
    "License"); you may not use this file except in compliance
    with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing,
    software distributed under the License is distributed on an
    "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
     KIND, either express or implied.  See the License for the
    specific language governing permissions and limitations
    under the License.
  -->
  <html>

  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <script src="js/home.js"></script>
    <link rel="stylesheet" type="text/css" href="css/home.css" />
    <title>Wed Up</title>
    
    <link href="css/forum/style.css" rel="stylesheet">
    <link href="css/forum/style-1.1.css" rel="stylesheet">
    <link href="css/forum/style-1.2.css" rel="stylesheet">
    <link href="css/forum/font-awesome/font-awesome.css" rel="stylesheet">
    <!--[if IE 7]>
        <link href="<?php echo $sk['config']['theme_url']; ?>/css/font-awesome/font-awesome-ie7.css" rel="stylesheet">
    <![endif]-->
      
    <script src="js/forum/jquery-ui-1.10.4.custom.min.js"></script>
    <script src="js/forum/jquery.ui.touch-punch.min.js"></script>
    <script src="js/forum/jquery-timeago.js"></script>
    <script src="js/forum/jquery.form.min.js"></script>
    <script>
    function SK_source(){
        return 'http://192.168.1.121/forum/Script/request.php';
    }
    function SK_pageSource() {
        return 'http://192.168.1.121/forum/Script/page.php';
    }
    </script>
    <script src="js/forum/script.js"></script>
</head>
<body>
    <style type="text/css">
        .ui-overlay-b, .ui-page-theme-b, .ui-page-theme-b .ui-panel-wrapper{
            text-shadow: none !important;
        }
        .header-wrapper {
            background:linear-gradient(#4C4C4C, #151515) !important;
            border-bottom: none !important;
            
        }
        .header-join-wrapper{
            color: white !important;
            display: none !important;
        }
        .header-user-info{
        	display: none !important;
        }
    </style>

    <?php echo SK_getPage('header/content'); ?>
    <div class="page-wrapper">
        <?php echo $sk['content']; ?>
    </div>    
</body>


</html>